version: '2'
services:
  balenaPhono:
    network_mode: host
    restart: always
    build: ./balenaPhono
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1
    ports:
      - "80:80/tcp"
      - "80:80/udp"
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.firmware: 1
