version: '2'
services:
  balenaPhono:
    network_mode: host
    restart: always
    build: ./balenaPhono
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - "80:80/tcp"
      - "80:80/udp"
  balenaBooter:
    build: ./booter
    environment:
      - 'REBOOT_SLEEP_TIME=1d'
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: 1
    command:
      - "/bin/sh"
      - "-c"
      - "sleep $REBOOT_SLEEP_TIME && dbus-send --system --print-reply --dest=org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.Reboot"
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
