FROM balenalib/raspberry-pi-debian-python:3.9-buster-run

WORKDIR /app

RUN install_packages alsa-utils darkice icecast2

# This will copy all files in our root to the working  directory in the container
COPY . ./

RUN python3 phonoConfig.py

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

# startup.sh will run when container starts up on the device
CMD ["bash", "start.sh"]