## booter/Dockerfile.template ##
## Sam Dennon//2023                ##

# Use balena base images, they have extra Charlie Unicorn magic built in!
FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.10.10-bullseye

# Set the working directory
WORKDIR /booter

# Install required packages
RUN install_packages tzdata cron dbus

RUN pip install requests python-dotenv pathlib

# Copy all the things
COPY . ./

# Start the booter
CMD ["bash", "/booter/booter.sh"]
